// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/smallfish06/korea-securities-api/pkg/broker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrokerWithExtras creates a new instance of MockBrokerWithExtras. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrokerWithExtras(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrokerWithExtras {
	mock := &MockBrokerWithExtras{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrokerWithExtras is an autogenerated mock type for the BrokerWithExtras type
type MockBrokerWithExtras struct {
	mock.Mock
}

type MockBrokerWithExtras_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrokerWithExtras) EXPECT() *MockBrokerWithExtras_Expecter {
	return &MockBrokerWithExtras_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) Authenticate(ctx context.Context, creds broker.Credentials) (*broker.Token, error) {
	ret := _mock.Called(ctx, creds)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *broker.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Credentials) (*broker.Token, error)); ok {
		return returnFunc(ctx, creds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Credentials) *broker.Token); ok {
		r0 = returnFunc(ctx, creds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, broker.Credentials) error); ok {
		r1 = returnFunc(ctx, creds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockBrokerWithExtras_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - creds broker.Credentials
func (_e *MockBrokerWithExtras_Expecter) Authenticate(ctx interface{}, creds interface{}) *MockBrokerWithExtras_Authenticate_Call {
	return &MockBrokerWithExtras_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, creds)}
}

func (_c *MockBrokerWithExtras_Authenticate_Call) Run(run func(ctx context.Context, creds broker.Credentials)) *MockBrokerWithExtras_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.Credentials
		if args[1] != nil {
			arg1 = args[1].(broker.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_Authenticate_Call) Return(token *broker.Token, err error) *MockBrokerWithExtras_Authenticate_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockBrokerWithExtras_Authenticate_Call) RunAndReturn(run func(ctx context.Context, creds broker.Credentials) (*broker.Token, error)) *MockBrokerWithExtras_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CancelOrder provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) CancelOrder(ctx context.Context, orderID string) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrokerWithExtras_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockBrokerWithExtras_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockBrokerWithExtras_Expecter) CancelOrder(ctx interface{}, orderID interface{}) *MockBrokerWithExtras_CancelOrder_Call {
	return &MockBrokerWithExtras_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderID)}
}

func (_c *MockBrokerWithExtras_CancelOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockBrokerWithExtras_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_CancelOrder_Call) Return(err error) *MockBrokerWithExtras_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrokerWithExtras_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) error) *MockBrokerWithExtras_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) GetBalance(ctx context.Context, accountID string) (*broker.Balance, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *broker.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*broker.Balance, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *broker.Balance); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBrokerWithExtras_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockBrokerWithExtras_Expecter) GetBalance(ctx interface{}, accountID interface{}) *MockBrokerWithExtras_GetBalance_Call {
	return &MockBrokerWithExtras_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, accountID)}
}

func (_c *MockBrokerWithExtras_GetBalance_Call) Run(run func(ctx context.Context, accountID string)) *MockBrokerWithExtras_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_GetBalance_Call) Return(balance *broker.Balance, err error) *MockBrokerWithExtras_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockBrokerWithExtras_GetBalance_Call) RunAndReturn(run func(ctx context.Context, accountID string) (*broker.Balance, error)) *MockBrokerWithExtras_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstrument provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) GetInstrument(ctx context.Context, market string, symbol string) (*broker.Instrument, error) {
	ret := _mock.Called(ctx, market, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrument")
	}

	var r0 *broker.Instrument
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*broker.Instrument, error)); ok {
		return returnFunc(ctx, market, symbol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *broker.Instrument); ok {
		r0 = returnFunc(ctx, market, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Instrument)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, market, symbol)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_GetInstrument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrument'
type MockBrokerWithExtras_GetInstrument_Call struct {
	*mock.Call
}

// GetInstrument is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
func (_e *MockBrokerWithExtras_Expecter) GetInstrument(ctx interface{}, market interface{}, symbol interface{}) *MockBrokerWithExtras_GetInstrument_Call {
	return &MockBrokerWithExtras_GetInstrument_Call{Call: _e.mock.On("GetInstrument", ctx, market, symbol)}
}

func (_c *MockBrokerWithExtras_GetInstrument_Call) Run(run func(ctx context.Context, market string, symbol string)) *MockBrokerWithExtras_GetInstrument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_GetInstrument_Call) Return(instrument *broker.Instrument, err error) *MockBrokerWithExtras_GetInstrument_Call {
	_c.Call.Return(instrument, err)
	return _c
}

func (_c *MockBrokerWithExtras_GetInstrument_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string) (*broker.Instrument, error)) *MockBrokerWithExtras_GetInstrument_Call {
	_c.Call.Return(run)
	return _c
}

// GetOHLCV provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) GetOHLCV(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts) ([]broker.OHLCV, error) {
	ret := _mock.Called(ctx, market, symbol, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetOHLCV")
	}

	var r0 []broker.OHLCV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, broker.OHLCVOpts) ([]broker.OHLCV, error)); ok {
		return returnFunc(ctx, market, symbol, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, broker.OHLCVOpts) []broker.OHLCV); ok {
		r0 = returnFunc(ctx, market, symbol, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.OHLCV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, broker.OHLCVOpts) error); ok {
		r1 = returnFunc(ctx, market, symbol, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_GetOHLCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOHLCV'
type MockBrokerWithExtras_GetOHLCV_Call struct {
	*mock.Call
}

// GetOHLCV is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
//   - opts broker.OHLCVOpts
func (_e *MockBrokerWithExtras_Expecter) GetOHLCV(ctx interface{}, market interface{}, symbol interface{}, opts interface{}) *MockBrokerWithExtras_GetOHLCV_Call {
	return &MockBrokerWithExtras_GetOHLCV_Call{Call: _e.mock.On("GetOHLCV", ctx, market, symbol, opts)}
}

func (_c *MockBrokerWithExtras_GetOHLCV_Call) Run(run func(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts)) *MockBrokerWithExtras_GetOHLCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 broker.OHLCVOpts
		if args[3] != nil {
			arg3 = args[3].(broker.OHLCVOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_GetOHLCV_Call) Return(oHLCVs []broker.OHLCV, err error) *MockBrokerWithExtras_GetOHLCV_Call {
	_c.Call.Return(oHLCVs, err)
	return _c
}

func (_c *MockBrokerWithExtras_GetOHLCV_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts) ([]broker.OHLCV, error)) *MockBrokerWithExtras_GetOHLCV_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) GetOrder(ctx context.Context, orderID string) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockBrokerWithExtras_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockBrokerWithExtras_Expecter) GetOrder(ctx interface{}, orderID interface{}) *MockBrokerWithExtras_GetOrder_Call {
	return &MockBrokerWithExtras_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderID)}
}

func (_c *MockBrokerWithExtras_GetOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockBrokerWithExtras_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_GetOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockBrokerWithExtras_GetOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockBrokerWithExtras_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*broker.OrderResult, error)) *MockBrokerWithExtras_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderFills provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) GetOrderFills(ctx context.Context, orderID string) ([]broker.OrderFill, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderFills")
	}

	var r0 []broker.OrderFill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]broker.OrderFill, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []broker.OrderFill); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.OrderFill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_GetOrderFills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderFills'
type MockBrokerWithExtras_GetOrderFills_Call struct {
	*mock.Call
}

// GetOrderFills is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockBrokerWithExtras_Expecter) GetOrderFills(ctx interface{}, orderID interface{}) *MockBrokerWithExtras_GetOrderFills_Call {
	return &MockBrokerWithExtras_GetOrderFills_Call{Call: _e.mock.On("GetOrderFills", ctx, orderID)}
}

func (_c *MockBrokerWithExtras_GetOrderFills_Call) Run(run func(ctx context.Context, orderID string)) *MockBrokerWithExtras_GetOrderFills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_GetOrderFills_Call) Return(orderFills []broker.OrderFill, err error) *MockBrokerWithExtras_GetOrderFills_Call {
	_c.Call.Return(orderFills, err)
	return _c
}

func (_c *MockBrokerWithExtras_GetOrderFills_Call) RunAndReturn(run func(ctx context.Context, orderID string) ([]broker.OrderFill, error)) *MockBrokerWithExtras_GetOrderFills_Call {
	_c.Call.Return(run)
	return _c
}

// GetPositions provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) GetPositions(ctx context.Context, accountID string) ([]broker.Position, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPositions")
	}

	var r0 []broker.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]broker.Position, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []broker.Position); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.Position)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_GetPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositions'
type MockBrokerWithExtras_GetPositions_Call struct {
	*mock.Call
}

// GetPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockBrokerWithExtras_Expecter) GetPositions(ctx interface{}, accountID interface{}) *MockBrokerWithExtras_GetPositions_Call {
	return &MockBrokerWithExtras_GetPositions_Call{Call: _e.mock.On("GetPositions", ctx, accountID)}
}

func (_c *MockBrokerWithExtras_GetPositions_Call) Run(run func(ctx context.Context, accountID string)) *MockBrokerWithExtras_GetPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_GetPositions_Call) Return(positions []broker.Position, err error) *MockBrokerWithExtras_GetPositions_Call {
	_c.Call.Return(positions, err)
	return _c
}

func (_c *MockBrokerWithExtras_GetPositions_Call) RunAndReturn(run func(ctx context.Context, accountID string) ([]broker.Position, error)) *MockBrokerWithExtras_GetPositions_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) GetQuote(ctx context.Context, market string, symbol string) (*broker.Quote, error) {
	ret := _mock.Called(ctx, market, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *broker.Quote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*broker.Quote, error)); ok {
		return returnFunc(ctx, market, symbol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *broker.Quote); ok {
		r0 = returnFunc(ctx, market, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Quote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, market, symbol)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockBrokerWithExtras_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
func (_e *MockBrokerWithExtras_Expecter) GetQuote(ctx interface{}, market interface{}, symbol interface{}) *MockBrokerWithExtras_GetQuote_Call {
	return &MockBrokerWithExtras_GetQuote_Call{Call: _e.mock.On("GetQuote", ctx, market, symbol)}
}

func (_c *MockBrokerWithExtras_GetQuote_Call) Run(run func(ctx context.Context, market string, symbol string)) *MockBrokerWithExtras_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_GetQuote_Call) Return(quote *broker.Quote, err error) *MockBrokerWithExtras_GetQuote_Call {
	_c.Call.Return(quote, err)
	return _c
}

func (_c *MockBrokerWithExtras_GetQuote_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string) (*broker.Quote, error)) *MockBrokerWithExtras_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyOrder provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) ModifyOrder(ctx context.Context, orderID string, req broker.ModifyOrderRequest) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, orderID, req)

	if len(ret) == 0 {
		panic("no return value specified for ModifyOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, broker.ModifyOrderRequest) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, orderID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, broker.ModifyOrderRequest) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, orderID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, broker.ModifyOrderRequest) error); ok {
		r1 = returnFunc(ctx, orderID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_ModifyOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyOrder'
type MockBrokerWithExtras_ModifyOrder_Call struct {
	*mock.Call
}

// ModifyOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - req broker.ModifyOrderRequest
func (_e *MockBrokerWithExtras_Expecter) ModifyOrder(ctx interface{}, orderID interface{}, req interface{}) *MockBrokerWithExtras_ModifyOrder_Call {
	return &MockBrokerWithExtras_ModifyOrder_Call{Call: _e.mock.On("ModifyOrder", ctx, orderID, req)}
}

func (_c *MockBrokerWithExtras_ModifyOrder_Call) Run(run func(ctx context.Context, orderID string, req broker.ModifyOrderRequest)) *MockBrokerWithExtras_ModifyOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 broker.ModifyOrderRequest
		if args[2] != nil {
			arg2 = args[2].(broker.ModifyOrderRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_ModifyOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockBrokerWithExtras_ModifyOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockBrokerWithExtras_ModifyOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string, req broker.ModifyOrderRequest) (*broker.OrderResult, error)) *MockBrokerWithExtras_ModifyOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBrokerWithExtras_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockBrokerWithExtras_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockBrokerWithExtras_Expecter) Name() *MockBrokerWithExtras_Name_Call {
	return &MockBrokerWithExtras_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockBrokerWithExtras_Name_Call) Run(run func()) *MockBrokerWithExtras_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrokerWithExtras_Name_Call) Return(s string) *MockBrokerWithExtras_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBrokerWithExtras_Name_Call) RunAndReturn(run func() string) *MockBrokerWithExtras_Name_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function for the type MockBrokerWithExtras
func (_mock *MockBrokerWithExtras) PlaceOrder(ctx context.Context, req broker.OrderRequest) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.OrderRequest) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.OrderRequest) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, broker.OrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrokerWithExtras_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MockBrokerWithExtras_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req broker.OrderRequest
func (_e *MockBrokerWithExtras_Expecter) PlaceOrder(ctx interface{}, req interface{}) *MockBrokerWithExtras_PlaceOrder_Call {
	return &MockBrokerWithExtras_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, req)}
}

func (_c *MockBrokerWithExtras_PlaceOrder_Call) Run(run func(ctx context.Context, req broker.OrderRequest)) *MockBrokerWithExtras_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.OrderRequest
		if args[1] != nil {
			arg1 = args[1].(broker.OrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrokerWithExtras_PlaceOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockBrokerWithExtras_PlaceOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockBrokerWithExtras_PlaceOrder_Call) RunAndReturn(run func(ctx context.Context, req broker.OrderRequest) (*broker.OrderResult, error)) *MockBrokerWithExtras_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}
