// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/smallfish06/krsec/pkg/broker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockinstrumentGetter creates a new instance of MockinstrumentGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockinstrumentGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockinstrumentGetter {
	mock := &MockinstrumentGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockinstrumentGetter is an autogenerated mock type for the instrumentGetter type
type MockinstrumentGetter struct {
	mock.Mock
}

type MockinstrumentGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockinstrumentGetter) EXPECT() *MockinstrumentGetter_Expecter {
	return &MockinstrumentGetter_Expecter{mock: &_m.Mock}
}

// GetInstrument provides a mock function for the type MockinstrumentGetter
func (_mock *MockinstrumentGetter) GetInstrument(ctx context.Context, market string, symbol string) (*broker.Instrument, error) {
	ret := _mock.Called(ctx, market, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrument")
	}

	var r0 *broker.Instrument
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*broker.Instrument, error)); ok {
		return returnFunc(ctx, market, symbol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *broker.Instrument); ok {
		r0 = returnFunc(ctx, market, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Instrument)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, market, symbol)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinstrumentGetter_GetInstrument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrument'
type MockinstrumentGetter_GetInstrument_Call struct {
	*mock.Call
}

// GetInstrument is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
func (_e *MockinstrumentGetter_Expecter) GetInstrument(ctx interface{}, market interface{}, symbol interface{}) *MockinstrumentGetter_GetInstrument_Call {
	return &MockinstrumentGetter_GetInstrument_Call{Call: _e.mock.On("GetInstrument", ctx, market, symbol)}
}

func (_c *MockinstrumentGetter_GetInstrument_Call) Run(run func(ctx context.Context, market string, symbol string)) *MockinstrumentGetter_GetInstrument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockinstrumentGetter_GetInstrument_Call) Return(instrument *broker.Instrument, err error) *MockinstrumentGetter_GetInstrument_Call {
	_c.Call.Return(instrument, err)
	return _c
}

func (_c *MockinstrumentGetter_GetInstrument_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string) (*broker.Instrument, error)) *MockinstrumentGetter_GetInstrument_Call {
	_c.Call.Return(run)
	return _c
}
