// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/smallfish06/kr-broker-api/pkg/broker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockorderGetter creates a new instance of MockorderGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockorderGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockorderGetter {
	mock := &MockorderGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockorderGetter is an autogenerated mock type for the orderGetter type
type MockorderGetter struct {
	mock.Mock
}

type MockorderGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockorderGetter) EXPECT() *MockorderGetter_Expecter {
	return &MockorderGetter_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockorderGetter
func (_mock *MockorderGetter) GetOrder(ctx context.Context, orderID string) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockorderGetter_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockorderGetter_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockorderGetter_Expecter) GetOrder(ctx interface{}, orderID interface{}) *MockorderGetter_GetOrder_Call {
	return &MockorderGetter_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderID)}
}

func (_c *MockorderGetter_GetOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockorderGetter_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockorderGetter_GetOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockorderGetter_GetOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockorderGetter_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*broker.OrderResult, error)) *MockorderGetter_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}
