// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/smallfish06/krsec/pkg/broker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockorderFillsGetter creates a new instance of MockorderFillsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockorderFillsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockorderFillsGetter {
	mock := &MockorderFillsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockorderFillsGetter is an autogenerated mock type for the orderFillsGetter type
type MockorderFillsGetter struct {
	mock.Mock
}

type MockorderFillsGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockorderFillsGetter) EXPECT() *MockorderFillsGetter_Expecter {
	return &MockorderFillsGetter_Expecter{mock: &_m.Mock}
}

// GetOrderFills provides a mock function for the type MockorderFillsGetter
func (_mock *MockorderFillsGetter) GetOrderFills(ctx context.Context, orderID string) ([]broker.OrderFill, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderFills")
	}

	var r0 []broker.OrderFill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]broker.OrderFill, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []broker.OrderFill); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.OrderFill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockorderFillsGetter_GetOrderFills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderFills'
type MockorderFillsGetter_GetOrderFills_Call struct {
	*mock.Call
}

// GetOrderFills is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockorderFillsGetter_Expecter) GetOrderFills(ctx interface{}, orderID interface{}) *MockorderFillsGetter_GetOrderFills_Call {
	return &MockorderFillsGetter_GetOrderFills_Call{Call: _e.mock.On("GetOrderFills", ctx, orderID)}
}

func (_c *MockorderFillsGetter_GetOrderFills_Call) Run(run func(ctx context.Context, orderID string)) *MockorderFillsGetter_GetOrderFills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockorderFillsGetter_GetOrderFills_Call) Return(orderFills []broker.OrderFill, err error) *MockorderFillsGetter_GetOrderFills_Call {
	_c.Call.Return(orderFills, err)
	return _c
}

func (_c *MockorderFillsGetter_GetOrderFills_Call) RunAndReturn(run func(ctx context.Context, orderID string) ([]broker.OrderFill, error)) *MockorderFillsGetter_GetOrderFills_Call {
	_c.Call.Return(run)
	return _c
}
