// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/smallfish06/krsec/pkg/broker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBroker creates a new instance of MockBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroker {
	mock := &MockBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBroker is an autogenerated mock type for the Broker type
type MockBroker struct {
	mock.Mock
}

type MockBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroker) EXPECT() *MockBroker_Expecter {
	return &MockBroker_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockBroker
func (_mock *MockBroker) Authenticate(ctx context.Context, creds broker.Credentials) (*broker.Token, error) {
	ret := _mock.Called(ctx, creds)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *broker.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Credentials) (*broker.Token, error)); ok {
		return returnFunc(ctx, creds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Credentials) *broker.Token); ok {
		r0 = returnFunc(ctx, creds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, broker.Credentials) error); ok {
		r1 = returnFunc(ctx, creds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBroker_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockBroker_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - creds broker.Credentials
func (_e *MockBroker_Expecter) Authenticate(ctx interface{}, creds interface{}) *MockBroker_Authenticate_Call {
	return &MockBroker_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, creds)}
}

func (_c *MockBroker_Authenticate_Call) Run(run func(ctx context.Context, creds broker.Credentials)) *MockBroker_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.Credentials
		if args[1] != nil {
			arg1 = args[1].(broker.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroker_Authenticate_Call) Return(token *broker.Token, err error) *MockBroker_Authenticate_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockBroker_Authenticate_Call) RunAndReturn(run func(ctx context.Context, creds broker.Credentials) (*broker.Token, error)) *MockBroker_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CancelOrder provides a mock function for the type MockBroker
func (_mock *MockBroker) CancelOrder(ctx context.Context, orderID string) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroker_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockBroker_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockBroker_Expecter) CancelOrder(ctx interface{}, orderID interface{}) *MockBroker_CancelOrder_Call {
	return &MockBroker_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderID)}
}

func (_c *MockBroker_CancelOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockBroker_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroker_CancelOrder_Call) Return(err error) *MockBroker_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroker_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) error) *MockBroker_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockBroker
func (_mock *MockBroker) GetBalance(ctx context.Context, accountID string) (*broker.Balance, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *broker.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*broker.Balance, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *broker.Balance); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBroker_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBroker_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockBroker_Expecter) GetBalance(ctx interface{}, accountID interface{}) *MockBroker_GetBalance_Call {
	return &MockBroker_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, accountID)}
}

func (_c *MockBroker_GetBalance_Call) Run(run func(ctx context.Context, accountID string)) *MockBroker_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroker_GetBalance_Call) Return(balance *broker.Balance, err error) *MockBroker_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockBroker_GetBalance_Call) RunAndReturn(run func(ctx context.Context, accountID string) (*broker.Balance, error)) *MockBroker_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOHLCV provides a mock function for the type MockBroker
func (_mock *MockBroker) GetOHLCV(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts) ([]broker.OHLCV, error) {
	ret := _mock.Called(ctx, market, symbol, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetOHLCV")
	}

	var r0 []broker.OHLCV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, broker.OHLCVOpts) ([]broker.OHLCV, error)); ok {
		return returnFunc(ctx, market, symbol, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, broker.OHLCVOpts) []broker.OHLCV); ok {
		r0 = returnFunc(ctx, market, symbol, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.OHLCV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, broker.OHLCVOpts) error); ok {
		r1 = returnFunc(ctx, market, symbol, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBroker_GetOHLCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOHLCV'
type MockBroker_GetOHLCV_Call struct {
	*mock.Call
}

// GetOHLCV is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
//   - opts broker.OHLCVOpts
func (_e *MockBroker_Expecter) GetOHLCV(ctx interface{}, market interface{}, symbol interface{}, opts interface{}) *MockBroker_GetOHLCV_Call {
	return &MockBroker_GetOHLCV_Call{Call: _e.mock.On("GetOHLCV", ctx, market, symbol, opts)}
}

func (_c *MockBroker_GetOHLCV_Call) Run(run func(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts)) *MockBroker_GetOHLCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 broker.OHLCVOpts
		if args[3] != nil {
			arg3 = args[3].(broker.OHLCVOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBroker_GetOHLCV_Call) Return(oHLCVs []broker.OHLCV, err error) *MockBroker_GetOHLCV_Call {
	_c.Call.Return(oHLCVs, err)
	return _c
}

func (_c *MockBroker_GetOHLCV_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string, opts broker.OHLCVOpts) ([]broker.OHLCV, error)) *MockBroker_GetOHLCV_Call {
	_c.Call.Return(run)
	return _c
}

// GetPositions provides a mock function for the type MockBroker
func (_mock *MockBroker) GetPositions(ctx context.Context, accountID string) ([]broker.Position, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPositions")
	}

	var r0 []broker.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]broker.Position, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []broker.Position); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broker.Position)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBroker_GetPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositions'
type MockBroker_GetPositions_Call struct {
	*mock.Call
}

// GetPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockBroker_Expecter) GetPositions(ctx interface{}, accountID interface{}) *MockBroker_GetPositions_Call {
	return &MockBroker_GetPositions_Call{Call: _e.mock.On("GetPositions", ctx, accountID)}
}

func (_c *MockBroker_GetPositions_Call) Run(run func(ctx context.Context, accountID string)) *MockBroker_GetPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroker_GetPositions_Call) Return(positions []broker.Position, err error) *MockBroker_GetPositions_Call {
	_c.Call.Return(positions, err)
	return _c
}

func (_c *MockBroker_GetPositions_Call) RunAndReturn(run func(ctx context.Context, accountID string) ([]broker.Position, error)) *MockBroker_GetPositions_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function for the type MockBroker
func (_mock *MockBroker) GetQuote(ctx context.Context, market string, symbol string) (*broker.Quote, error) {
	ret := _mock.Called(ctx, market, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *broker.Quote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*broker.Quote, error)); ok {
		return returnFunc(ctx, market, symbol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *broker.Quote); ok {
		r0 = returnFunc(ctx, market, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.Quote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, market, symbol)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBroker_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockBroker_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - market string
//   - symbol string
func (_e *MockBroker_Expecter) GetQuote(ctx interface{}, market interface{}, symbol interface{}) *MockBroker_GetQuote_Call {
	return &MockBroker_GetQuote_Call{Call: _e.mock.On("GetQuote", ctx, market, symbol)}
}

func (_c *MockBroker_GetQuote_Call) Run(run func(ctx context.Context, market string, symbol string)) *MockBroker_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBroker_GetQuote_Call) Return(quote *broker.Quote, err error) *MockBroker_GetQuote_Call {
	_c.Call.Return(quote, err)
	return _c
}

func (_c *MockBroker_GetQuote_Call) RunAndReturn(run func(ctx context.Context, market string, symbol string) (*broker.Quote, error)) *MockBroker_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyOrder provides a mock function for the type MockBroker
func (_mock *MockBroker) ModifyOrder(ctx context.Context, orderID string, req broker.ModifyOrderRequest) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, orderID, req)

	if len(ret) == 0 {
		panic("no return value specified for ModifyOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, broker.ModifyOrderRequest) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, orderID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, broker.ModifyOrderRequest) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, orderID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, broker.ModifyOrderRequest) error); ok {
		r1 = returnFunc(ctx, orderID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBroker_ModifyOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyOrder'
type MockBroker_ModifyOrder_Call struct {
	*mock.Call
}

// ModifyOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - req broker.ModifyOrderRequest
func (_e *MockBroker_Expecter) ModifyOrder(ctx interface{}, orderID interface{}, req interface{}) *MockBroker_ModifyOrder_Call {
	return &MockBroker_ModifyOrder_Call{Call: _e.mock.On("ModifyOrder", ctx, orderID, req)}
}

func (_c *MockBroker_ModifyOrder_Call) Run(run func(ctx context.Context, orderID string, req broker.ModifyOrderRequest)) *MockBroker_ModifyOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 broker.ModifyOrderRequest
		if args[2] != nil {
			arg2 = args[2].(broker.ModifyOrderRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBroker_ModifyOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockBroker_ModifyOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockBroker_ModifyOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string, req broker.ModifyOrderRequest) (*broker.OrderResult, error)) *MockBroker_ModifyOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockBroker
func (_mock *MockBroker) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBroker_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockBroker_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockBroker_Expecter) Name() *MockBroker_Name_Call {
	return &MockBroker_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockBroker_Name_Call) Run(run func()) *MockBroker_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroker_Name_Call) Return(s string) *MockBroker_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBroker_Name_Call) RunAndReturn(run func() string) *MockBroker_Name_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function for the type MockBroker
func (_mock *MockBroker) PlaceOrder(ctx context.Context, req broker.OrderRequest) (*broker.OrderResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 *broker.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.OrderRequest) (*broker.OrderResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.OrderRequest) *broker.OrderResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.OrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, broker.OrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBroker_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MockBroker_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req broker.OrderRequest
func (_e *MockBroker_Expecter) PlaceOrder(ctx interface{}, req interface{}) *MockBroker_PlaceOrder_Call {
	return &MockBroker_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, req)}
}

func (_c *MockBroker_PlaceOrder_Call) Run(run func(ctx context.Context, req broker.OrderRequest)) *MockBroker_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.OrderRequest
		if args[1] != nil {
			arg1 = args[1].(broker.OrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroker_PlaceOrder_Call) Return(orderResult *broker.OrderResult, err error) *MockBroker_PlaceOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockBroker_PlaceOrder_Call) RunAndReturn(run func(ctx context.Context, req broker.OrderRequest) (*broker.OrderResult, error)) *MockBroker_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}
